site_name: Bioinformatics Tutorials@SLU BI1324 (30224), 2020
theme:
    name: 'material'
    palette:
        primary: 'blue'
        accent: 'blue'
repo_name: 'domenico-simone/tutorials'
repo_url: 'https://github.com/domenico-simone/tutorials'

extra:
    social:
        - type: 'github'
          link: 'https://github.com/HadrienG'
        - type: 'twitter'
          link: 'https://twitter.com/HGourle'

# extensions
markdown_extensions:
    - admonition
    - codehilite
    - markdown.extensions.toc:
        permalink: true

# page tree
pages:
    - Home: index.md
    - Individual lessons:
        - The command-line: command_line.md
        - File Formats: file_formats.md
        - Quality Control and Trimming: qc.md
        - Mapping and Variant Calling: mapping.md
        - De-novo Genome Assembly: assembly.md
        - Genome Annotation: annotation.md
        - Pan-Genome Analysis: pan_genome.md
        - Metabarcoding: 16S.md
        - Whole Metagenome Sequencing: wms.md
        - Metagenome assembly: meta_assembly.md
        - Metagenome assembly (continued): meta_assembly_2.md
        - Viral metagenomics: metavir.md
        - RNA-Seq: rna.md
        - Introduction to Nanopore Sequencing: nanopore.md
